platforms:
- name: t2
  repo: https://github.com/tuya/TuyaOpen-T2
  commit: master

- name: t3
  repo: https://github.com/tuya/TuyaOpen-T3
  commit: master

- name: ubuntu
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  commit: platform_ubuntu

- name: t5ai
  repo: https://github.com/tuya/TuyaOpen-T5AI.git
  commit: master

- name: esp32
  repo: https://github.com/tuya/TuyaOpen-esp32
  commit: master
  chip:
    - esp32
    - esp32c3
    - esp32s3

- name: ln882h
  repo: https://github.com/tuya/TuyaOpen-ln882h
  commit: master

- name: bk7231x
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  commit: master
  chip:
    - bk7231n
