platforms:
- name: T2
  repo: https://github.com/tuya/TuyaOpen-T2
  branch: master
  commit: c3b1c191256badfcdac2db6f4381278e9b260636

- name: T3
  repo: https://github.com/tuya/TuyaOpen-T3
  branch: master
  commit: 2217df0cbc02b1a15687936088ce6f096e2c4bb7

- name: Ubuntu
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  branch: platform_ubuntu
  commit: a53d513e702fbb40ee40ee6e748f8930b9c113d0

- name: T5AI
  repo: https://github.com/tuya/TuyaOpen-T5AI
  branch: master
  commit: 80c4447d0c6866d5e76de61be596221eec856503

- name: ESP32
  repo: https://github.com/tuya/TuyaOpen-esp32
  branch: master
  commit: 10efde64edd5c1e35e947cb0f6cec1fafe8b6c1d

- name: LN882H
  repo: https://github.com/tuya/TuyaOpen-ln882h
  branch: master
  commit: deb153bd7de5a35f4a4dd1a1d098f2ccdb70813a

- name: BK7231X
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  branch: master
  commit: dd167974c5e9ba96f6216f856b2009164a18caa8
